# Generated by Django 4.2.16 on 2024-10-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcost',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorcost',
            name='payment_upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorcost',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
