# Generated by Django 4.2.16 on 2024-10-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_vendorcost_address_vendorcost_payment_upi_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorcost',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendorcost',
            name='payment_upi_id',
        ),
        migrations.RemoveField(
            model_name='vendorcost',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
