# Generated by Django 4.2.16 on 2024-10-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcost',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
